public class $CLIENT_CLASSNAME$ {

    private $PROTOTYPE_CLASSNAME$ $PROTOTYPE_INSTANCE_NAME$;

    public $CLIENT_CLASSNAME$($PROTOTYPE_CLASSNAME$ $PROTOTYPE_INSTANCE_NAME$){
        this.$PROTOTYPE_INSTANCE_NAME$ = $PROTOTYPE_INSTANCE_NAME$;
    }
    public void $OPERATION_METHOD_NAME$(){
        //some logic
        $PROTOTYPE_CLASSNAME$ p = $PROTOTYPE_INSTANCE_NAME$.$CLONE_METHOD_NAME$();
    }
}
